### ISSUE TITLE
_buttons.scss

### ISSUE THREAD

**Issue by mtsweir** [space150/spaceBase#57]
In the this partial for the first '&' it appends .btn to .btn:hover and .btn:focus

  &,
  &:hover,
  &:focus { 
    text-decoration: none;
    background-color: darken($secondary, 10%);
  }

So the output for example is:
.btn, .btn:hover, .btn:focus {
    text-decoration: none;
    background-color: #c20045;
}

I had to remove the first '&' symbol which removed the .btn default getting included.

**Comment by cstoobes** [comment]
We don't normally want underlines on our buttons, so this was intentional. But if you only want a background color on the hover state, then your change is correct.

The beauty of spaceBase is that files in the `/ui` folder are just boilerplate styles, feel free to edit them to suit your particular design!
